
artifacts_root: artifacts


data_ingestion:
   root_dir: artifacts/data_ingestion
   source_url: https://github.com/Josmin123/datasets/raw/main/samsum%20datasets.zip
   local_data_file: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion